MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/home/zppmt/maskrcnn-benchmark/configs/detail/new_keypoint_weights.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 60
  ROI_KEYPOINT_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "KeypointRCNNFeatureExtractor"
    PREDICTOR: "KeypointRCNNPredictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 56
    SHARE_BOX_FEATURE_EXTRACTOR: False
    NUM_CLASSES : 14
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNConv1x1Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 14
    SHARE_BOX_FEATURE_EXTRACTOR: False
  ROI_IMAGEMASK_HEAD:
    PREDICTOR: "MaskRCNNFPNImageMaskPredictor"
    NUM_CLASSES: 459 # TODO, w detailu jest 0-458, ale chyba nie przeszkadza jak ulatwimy indeksowanie +1)
  KEYPOINT_ON: True
  MASK_ON: True
  IMAGEMASK_ON: False
DATASETS:
  TRAIN: ("coco_detail_keypoints",)
#   TRAIN: ("keypoints_coco_2014_train",)
#  TRAIN: ("coco_2017_val", "keypoints_coco_2017_val",)
#  TRAIN: ("keypoints_coco_2017_val",)
#  TEST:
INPUT:
  MAX_SIZE_TEST: 500
  MIN_SIZE_TEST: 100
  MAX_SIZE_TRAIN: 500
  MIN_SIZE_TRAIN: (100,160)
DATALOADER:
  SIZE_DIVISIBILITY: 32
OUTPUT_DIR: "./trash2"
SOLVER:
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (7500, 10000)
  MAX_ITER: 10000
  IMS_PER_BATCH: 1
TEST:
  IMS_PER_BATCH: 2
